import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import Head from 'next/head'
import { useRouter } from 'next/router'
import styles from '../../../styles/Home.module.css'
import { OgpBox } from '../../../components/OgpBox'
import { getBookmarkByIdAsync } from '../../../lib/index'

export default function Details() {
  const router = useRouter()
  const { id } = router.query

  const [bookmark, setBookmark] = useState<any>(undefined);
  const [relatedBookmark, setRelated] = useState<Array<any>>([]);
  const [isLoading, setLoading] = useState<boolean>(true);

  useEffect(() => {
    if(!Number(id)) return
    const f = async () => {
      const res = await getBookmarkByIdAsync(Number(id));
      setBookmark(res.bookmark)
      setRelated(res.related)
      setLoading(false)
    }
    f();
  }, [id])

  const RelatedBookmarkList = relatedBookmark.map((item: any) => {
    return item.ogp.hasOwnProperty('og:title')?
    (<Link href="/bookmarks/[id]" as={`/bookmarks/${item.id}`} key={item.id}>
      <a>
        <OgpBox ogp={item.ogp} />
      </a>
    </Link>)
    : null
  })


  return (
    <div>
      <Head>
        <title>栞 - Shiori -</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>
        <h1 className={styles.title}>栞 - Shiori -</h1>
        {
          isLoading?
          null :
          <div className={styles.content}>
            <a href={bookmark.url} target="_blank" rel="noopener noreferrer">
              <OgpBox ogp={bookmark.ogp} />
            </a>
            <p className={styles.memoTitle}>memo</p>
            <p className={styles.memo}>{bookmark.memo}</p>
            <hr />
            {RelatedBookmarkList}
          </div>
        }
      </main>
    </div>
  )
}
